name: Issue watcher

# Author: @minff
# Issue : n/a
# Desc  : This workflow reads issue with label add-api and then add API 

# run this on push to main
on:
  issues:
  issue_comment:

jobs:

  show_issue_event:
    name: Show event
    runs-on: ubuntu-latest
    steps:
      - name: show github
        run: |
          echo ${{ toJson(github.event.action) }}
          echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: show issue event
        run: |
          echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.issue) }}
      - name: show issue comment event
        run: |
          echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.issue_comment) }}