name: Issue watcher

# Author: @minff
# Issue : n/a
# Desc  : This workflow reads issue with label add-api and then add API 

on:
  issues:
    types:
      - labeled

jobs:
  add_api:
    uses: mobidatalab/mdl-catalog-deployment/.github/workflows/base_issue.yaml@main

